language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
  - npm install

script:
  - npm run build
  - echo "$NPM_PASSWORD" | npm login -Username "$NPM_USERNAME" --password-stdin
  - npm publish
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t fefeng/resource:latest .
  - docker push fefeng/resource:latest